[features]
seeds = false
skip-lint = false
[programs.localnet]
usvoting = "2yh64WuwZYVJmsvgYn7g1vtXr9rzKg1HJqXok3hUVZ3n"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/kakkoii4cat/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
